<a href="https://colab.research.google.com/github/GabrielAzpitarte/Machine-learning-projects/blob/main/text_generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Les données

### Les imports

In [ ]:
# Les imports de base pour retrvailler l'IA
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# On aura besoin de tensorflow
import tensorflow as tf

In [ ]:
# Importer nos données
chemin = 'LesMiserables.txt'

In [ ]:
# Lire notre fichier
texte = open(chemin, 'r').read()

In [ ]:
# nbre de caracteres dans mon texte (1 million commence a être bien pour entrainer son IA)
len(texte)

2468231

In [ ]:
# Un oeil au texte (les 500 premiers caracteres)
texte[:500]

"Chapitre I\n\nMonsieur Myriel\n\n\nEn 1815, M. Charles-François-Bienvenu Myriel était évêque de Digne.\nC'était un vieillard d'environ soixante-quinze ans; il occupait le siège\nde Digne depuis 1806.\n\nQuoique ce détail ne touche en aucune manière au fond même de ce que\nnous avons à raconter, il n'est peut-être pas inutile, ne fût-ce que\npour être exact en tout, d'indiquer ici les bruits et les propos qui\navaient couru sur son compte au moment où il était arrivé dans le\ndiocèse. Vrai ou faux, ce qu'on d"

In [ ]:
# Si à la place on le print, on voit la structure du texte, espaces, sauts de lignes etc
print(texte[:500])

Chapitre I

Monsieur Myriel


En 1815, M. Charles-François-Bienvenu Myriel était évêque de Digne.
C'était un vieillard d'environ soixante-quinze ans; il occupait le siège
de Digne depuis 1806.

Quoique ce détail ne touche en aucune manière au fond même de ce que
nous avons à raconter, il n'est peut-être pas inutile, ne fût-ce que
pour être exact en tout, d'indiquer ici les bruits et les propos qui
avaient couru sur son compte au moment où il était arrivé dans le
diocèse. Vrai ou faux, ce qu'on d


In [ ]:
# Afficher un morceau de texte au hasard
print(texte[12000:12500])

ement lui doit pour ses frais de
carrosse en ville et de tournées dans le diocèse. Pour les évêques
d'autrefois c'était l'usage.

--Tiens! dit l'évêque, vous avez raison, madame Magloire.

Il fit sa réclamation.

Quelque temps après, le conseil général, prenant cette demande en
considération, lui vota une somme annuelle de trois mille francs, sous
cette rubrique: _Allocation à M. l'évêque pour frais de carrosse, frais
de poste et frais de tournées pastorales_.

Cela fit beaucoup crier la bourgeo


### Les caracteres uniques

In [ ]:
# Convertir le texte en un set
set(texte)

{'\n',
 ' ',
 '!',
 '"',
 "'",
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '«',
 '°',
 'º',
 '»',
 'À',
 'Â',
 'Ç',
 'È',
 'É',
 'Ê',
 'Ô',
 'à',
 'â',
 'æ',
 'ç',
 'è',
 'é',
 'ê',
 'ë',
 'î',
 'ï',
 'ñ',
 'ô',
 'ö',
 'ù',
 'û',
 'ü'}

In [ ]:
# Trier ce set par ordre
sorted(set(texte))

['\n',
 ' ',
 '!',
 '"',
 "'",
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '«',
 '°',
 'º',
 '»',
 'À',
 'Â',
 'Ç',
 'È',
 'É',
 'Ê',
 'Ô',
 'à',
 'â',
 'æ',
 'ç',
 'è',
 'é',
 'ê',
 'ë',
 'î',
 'ï',
 'ñ',
 'ô',
 'ö',
 'ù',
 'û',
 'ü']

In [ ]:
# On stocke notre set dans une variable pour l'appeler plus facilement
vocabulaire = sorted(set(texte))
print(vocabulaire)

['\n', ' ', '!', '"', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '«', '°', 'º', '»', 'À', 'Â', 'Ç', 'È', 'É', 'Ê', 'Ô', 'à', 'â', 'æ', 'ç', 'è', 'é', 'ê', 'ë', 'î', 'ï', 'ñ', 'ô', 'ö', 'ù', 'û', 'ü']


In [ ]:
# hs : ici vous auriez pu voir le nbre de caractere
len(vocabulaire)

105

# Traitement du texte et vectorisation

Vectoriser le texte et créer un dictionnaire d'encodage

In [ ]:
# On boucle sur chaque pair (caractere / son numéro)
for pair in enumerate(vocabulaire):
  print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, "'")
(5, '(')
(6, ')')
(7, '*')
(8, ',')
(9, '-')
(10, '.')
(11, '/')
(12, '0')
(13, '1')
(14, '2')
(15, '3')
(16, '4')
(17, '5')
(18, '6')
(19, '7')
(20, '8')
(21, '9')
(22, ':')
(23, ';')
(24, '?')
(25, 'A')
(26, 'B')
(27, 'C')
(28, 'D')
(29, 'E')
(30, 'F')
(31, 'G')
(32, 'H')
(33, 'I')
(34, 'J')
(35, 'K')
(36, 'L')
(37, 'M')
(38, 'N')
(39, 'O')
(40, 'P')
(41, 'Q')
(42, 'R')
(43, 'S')
(44, 'T')
(45, 'U')
(46, 'V')
(47, 'W')
(48, 'X')
(49, 'Y')
(50, 'Z')
(51, '_')
(52, 'a')
(53, 'b')
(54, 'c')
(55, 'd')
(56, 'e')
(57, 'f')
(58, 'g')
(59, 'h')
(60, 'i')
(61, 'j')
(62, 'k')
(63, 'l')
(64, 'm')
(65, 'n')
(66, 'o')
(67, 'p')
(68, 'q')
(69, 'r')
(70, 's')
(71, 't')
(72, 'u')
(73, 'v')
(74, 'w')
(75, 'x')
(76, 'y')
(77, 'z')
(78, '«')
(79, '°')
(80, 'º')
(81, '»')
(82, 'À')
(83, 'Â')
(84, 'Ç')
(85, 'È')
(86, 'É')
(87, 'Ê')
(88, 'Ô')
(89, 'à')
(90, 'â')
(91, 'æ')
(92, 'ç')
(93, 'è')
(94, 'é')
(95, 'ê')
(96, 'ë')
(97, 'î')
(98, 'ï')
(99, 'ñ')
(100, 'ô'

On va utiliser cette logique pour générer un dictionnaire qui passe d'un caractère à un index

In [ ]:
caractere_par_index = {caractere:index for index, caractere in enumerate(vocabulaire)}

#J'affiche le résultat en colonne (pour l'avoir en ligne j'aurais mis print())
caractere_par_index

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 "'": 4,
 '(': 5,
 ')': 6,
 '*': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '/': 11,
 '0': 12,
 '1': 13,
 '2': 14,
 '3': 15,
 '4': 16,
 '5': 17,
 '6': 18,
 '7': 19,
 '8': 20,
 '9': 21,
 ':': 22,
 ';': 23,
 '?': 24,
 'A': 25,
 'B': 26,
 'C': 27,
 'D': 28,
 'E': 29,
 'F': 30,
 'G': 31,
 'H': 32,
 'I': 33,
 'J': 34,
 'K': 35,
 'L': 36,
 'M': 37,
 'N': 38,
 'O': 39,
 'P': 40,
 'Q': 41,
 'R': 42,
 'S': 43,
 'T': 44,
 'U': 45,
 'V': 46,
 'W': 47,
 'X': 48,
 'Y': 49,
 'Z': 50,
 '_': 51,
 'a': 52,
 'b': 53,
 'c': 54,
 'd': 55,
 'e': 56,
 'f': 57,
 'g': 58,
 'h': 59,
 'i': 60,
 'j': 61,
 'k': 62,
 'l': 63,
 'm': 64,
 'n': 65,
 'o': 66,
 'p': 67,
 'q': 68,
 'r': 69,
 's': 70,
 't': 71,
 'u': 72,
 'v': 73,
 'w': 74,
 'x': 75,
 'y': 76,
 'z': 77,
 '«': 78,
 '°': 79,
 'º': 80,
 '»': 81,
 'À': 82,
 'Â': 83,
 'Ç': 84,
 'È': 85,
 'É': 86,
 'Ê': 87,
 'Ô': 88,
 'à': 89,
 'â': 90,
 'æ': 91,
 'ç': 92,
 'è': 93,
 'é': 94,
 'ê': 95,
 'ë': 96,
 'î': 97,
 'ï': 98,
 'ñ': 99,
 'ô': 100

In [ ]:
# Si je veux l'index numérique de la lettre G majuscule
caractere_par_index['G']

31

Inverse : index par caractere

In [ ]:
# On cherche a ce que la variable vocabulaire devienne un appel d'index
index_par_caractere = np.array(vocabulaire)

In [ ]:
index_par_caractere[31]

'G'

Encoder tout le texte avec des entiers

In [ ]:
encode_texte = np.array([caractere_par_index[caractere] for caractere in texte])

In [ ]:
# Affichons le
encode_texte

array([27, 59, 52, ..., 56, 10,  0])

In [ ]:
# en print
print(encode_texte)

[27 59 52 ... 56 10  0]


In [ ]:
# HS
encode_texte.shape

(2468231,)

- Exemple sur un échantillon

In [ ]:
echantillon = texte[:500]
print(echantillon)

Chapitre I

Monsieur Myriel


En 1815, M. Charles-François-Bienvenu Myriel était évêque de Digne.
C'était un vieillard d'environ soixante-quinze ans; il occupait le siège
de Digne depuis 1806.

Quoique ce détail ne touche en aucune manière au fond même de ce que
nous avons à raconter, il n'est peut-être pas inutile, ne fût-ce que
pour être exact en tout, d'indiquer ici les bruits et les propos qui
avaient couru sur son compte au moment où il était arrivé dans le
diocèse. Vrai ou faux, ce qu'on d


In [ ]:
# Version encodée
print(encode_texte[:500])

[ 27  59  52  67  60  71  69  56   1  33   0   0  37  66  65  70  60  56
  72  69   1  37  76  69  60  56  63   0   0   0  29  65   1  13  20  13
  17   8   1  37  10   1  27  59  52  69  63  56  70   9  30  69  52  65
  92  66  60  70   9  26  60  56  65  73  56  65  72   1  37  76  69  60
  56  63   1  94  71  52  60  71   1  94  73  95  68  72  56   1  55  56
   1  28  60  58  65  56  10   0  27   4  94  71  52  60  71   1  72  65
   1  73  60  56  60  63  63  52  69  55   1  55   4  56  65  73  60  69
  66  65   1  70  66  60  75  52  65  71  56   9  68  72  60  65  77  56
   1  52  65  70  23   1  60  63   1  66  54  54  72  67  52  60  71   1
  63  56   1  70  60  93  58  56   0  55  56   1  28  60  58  65  56   1
  55  56  67  72  60  70   1  13  20  12  18  10   0   0  41  72  66  60
  68  72  56   1  54  56   1  55  94  71  52  60  63   1  65  56   1  71
  66  72  54  59  56   1  56  65   1  52  72  54  72  65  56   1  64  52
  65  60  93  69  56   1  52  72   1  57  66  65  5

# Création des batches

Pour rappel : notre modèle se base sur le caractère

In [ ]:
print(texte[:500])

Chapitre I

Monsieur Myriel


En 1815, M. Charles-François-Bienvenu Myriel était évêque de Digne.
C'était un vieillard d'environ soixante-quinze ans; il occupait le siège
de Digne depuis 1806.

Quoique ce détail ne touche en aucune manière au fond même de ce que
nous avons à raconter, il n'est peut-être pas inutile, ne fût-ce que
pour être exact en tout, d'indiquer ici les bruits et les propos qui
avaient couru sur son compte au moment où il était arrivé dans le
diocèse. Vrai ou faux, ce qu'on d


In [ ]:
#Prenons une ligne de notre chapitre 1
ligne = "En 1815, M. Charles-François-Bienvenu Myriel était évêque de Digne."
# Regardons la longueur
len(ligne)

67

In [ ]:
# nbre de caractere pour une sequence de la taille de mon premier paragraphe
lignes = '''
En 1815, M. Charles-François-Bienvenu Myriel était évêque de Digne.
C'était un vieillard d'environ soixante-quinze ans; il occupait le siège
de Digne depuis 1806.
  '''

len(lignes)

166

In [ ]:
# Autre bout de texte
lignes_bis = '''
Quoique ce détail ne touche en aucune manière au fond même de ce que
nous avons à raconter, il n'est peut-être pas inutile, ne fût-ce que
pour être exact en tout, d'indiquer ici les bruits et les propos qui
avaient couru sur son compte au moment où il était arrivé dans le
diocèse.
  '''

len(lignes_bis)

285

Mon choix perso :
- un cas à 150 caracteres
- 2e cas à 250

In [ ]:
sequence_len = 250

Calculons le nbre total de séquences dans notre texte

In [ ]:
# On prendre la longueur totale du texte
# // -> permet une division qui arrondit le résultat en nombre entier
# +1 falcutatif, je cherche a enlever l'index 0 pour d'éventuelles erreurs futures
nb_sequences_totales = len(texte) // (sequence_len+1)

# On affiche le résultat
print(nb_sequences_totales)


9833


# Création des séquences

On va créer les séquences d'entrainbement grace à l'objet spécial Dataset de tensorflow

In [ ]:
# On appelle tf.data.Dataset
#On le construit avec from_tensor_slices()
# On lui passe la variable du texte encodé
dataset_caractere = tf.data.Dataset.from_tensor_slices(encode_texte)

In [ ]:
# Verifions le type de la variable dataset_caractere
type(dataset_caractere)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

On va utiliser la méthode "batch"

In [ ]:
for item in dataset_caractere.take(500):
  # On affiche ces éléments en numpy
  print(item.numpy())

27
59
52
67
60
71
69
56
1
33
0
0
37
66
65
70
60
56
72
69
1
37
76
69
60
56
63
0
0
0
29
65
1
13
20
13
17
8
1
37
10
1
27
59
52
69
63
56
70
9
30
69
52
65
92
66
60
70
9
26
60
56
65
73
56
65
72
1
37
76
69
60
56
63
1
94
71
52
60
71
1
94
73
95
68
72
56
1
55
56
1
28
60
58
65
56
10
0
27
4
94
71
52
60
71
1
72
65
1
73
60
56
60
63
63
52
69
55
1
55
4
56
65
73
60
69
66
65
1
70
66
60
75
52
65
71
56
9
68
72
60
65
77
56
1
52
65
70
23
1
60
63
1
66
54
54
72
67
52
60
71
1
63
56
1
70
60
93
58
56
0
55
56
1
28
60
58
65
56
1
55
56
67
72
60
70
1
13
20
12
18
10
0
0
41
72
66
60
68
72
56
1
54
56
1
55
94
71
52
60
63
1
65
56
1
71
66
72
54
59
56
1
56
65
1
52
72
54
72
65
56
1
64
52
65
60
93
69
56
1
52
72
1
57
66
65
55
1
64
95
64
56
1
55
56
1
54
56
1
68
72
56
0
65
66
72
70
1
52
73
66
65
70
1
89
1
69
52
54
66
65
71
56
69
8
1
60
63
1
65
4
56
70
71
1
67
56
72
71
9
95
71
69
56
1
67
52
70
1
60
65
72
71
60
63
56
8
1
65
56
1
57
103
71
9
54
56
1
68
72
56
0
67
66
72
69
1
95
71
69
56
1
56
75
52
54
71
1
56
65
1
71
66
72
71
8
1
55

In [ ]:
# Inversons
for item in dataset_caractere.take(500):
  print(index_par_caractere[item.numpy()])

C
h
a
p
i
t
r
e
 
I




M
o
n
s
i
e
u
r
 
M
y
r
i
e
l






E
n
 
1
8
1
5
,
 
M
.
 
C
h
a
r
l
e
s
-
F
r
a
n
ç
o
i
s
-
B
i
e
n
v
e
n
u
 
M
y
r
i
e
l
 
é
t
a
i
t
 
é
v
ê
q
u
e
 
d
e
 
D
i
g
n
e
.


C
'
é
t
a
i
t
 
u
n
 
v
i
e
i
l
l
a
r
d
 
d
'
e
n
v
i
r
o
n
 
s
o
i
x
a
n
t
e
-
q
u
i
n
z
e
 
a
n
s
;
 
i
l
 
o
c
c
u
p
a
i
t
 
l
e
 
s
i
è
g
e


d
e
 
D
i
g
n
e
 
d
e
p
u
i
s
 
1
8
0
6
.




Q
u
o
i
q
u
e
 
c
e
 
d
é
t
a
i
l
 
n
e
 
t
o
u
c
h
e
 
e
n
 
a
u
c
u
n
e
 
m
a
n
i
è
r
e
 
a
u
 
f
o
n
d
 
m
ê
m
e
 
d
e
 
c
e
 
q
u
e


n
o
u
s
 
a
v
o
n
s
 
à
 
r
a
c
o
n
t
e
r
,
 
i
l
 
n
'
e
s
t
 
p
e
u
t
-
ê
t
r
e
 
p
a
s
 
i
n
u
t
i
l
e
,
 
n
e
 
f
û
t
-
c
e
 
q
u
e


p
o
u
r
 
ê
t
r
e
 
e
x
a
c
t
 
e
n
 
t
o
u
t
,
 
d
'
i
n
d
i
q
u
e
r
 
i
c
i
 
l
e
s
 
b
r
u
i
t
s
 
e
t
 
l
e
s
 
p
r
o
p
o
s
 
q
u
i


a
v
a
i
e
n
t
 
c
o
u
r
u
 
s
u
r
 
s
o
n
 
c
o
m
p
t
e
 
a
u
 
m
o
m
e
n
t
 
o
ù
 
i
l
 
é
t
a
i
t
 
a
r
r
i
v
é
 
d
a
n
s
 
l
e


d
i
o
c
è
s
e
.
 
V
r
a
i
 
o
u
 
f
a
u
x
,
 
c
e
 
q
u
'
o
n
 
d


Création des séquences à partir du dataset créé

In [ ]:
# Méthode batch() pour additionner les éléments consécutis du dataset en batches
# drop_remainder sur True pour éliminer les caractères restants, ne pouvant faire un lot de
# 150 caractères au complet
sequences = dataset_caractere.batch(sequence_len+1, drop_remainder=True)

Toutes nos séquences :
- on va saisir la séquence de texte d'entrée
- Ensuite assigner la séquence de texte cible en tant que séquence de texte d'entrée décalée d'un pas en avant



In [ ]:
# Fonction pour créer des sequences ciblées
def create_sequences_ciblees(sequence):
  #Le texte d'entrée sera = a la sequence depuis le début (:) jusqu'au dernier caractère non inclus (-1)
  input_texte = sequence[:-1] #Bonjou
  # On assigne la séquence de texte cible, en la rendant = à la séquence décalée d'un pas en avant
  cible_texte = sequence[1:]  #onjour
  # On retourne le résultat
  return input_texte, cible_texte


In [ ]:
# On mappe tout ça a toutes les séquences
dataset = sequences.map(create_sequences_ciblees)

Exemple pour à quoi ca ressemble

In [ ]:
for input_texte, cible_texte in dataset.take(1):
  # Afficher l'input_texte en tableau numpy
  print(input_texte.numpy())
  print(index_par_caractere[input_texte.numpy()])

[27 59 52 67 60 71 69 56  1 33  0  0 37 66 65 70 60 56 72 69  1 37 76 69
 60 56 63  0  0  0 29 65  1 13 20 13 17  8  1 37 10  1 27 59 52 69 63 56
 70  9 30 69 52 65 92 66 60 70  9 26 60 56 65 73 56 65 72  1 37 76 69 60
 56 63  1 94 71 52 60 71  1 94 73 95 68 72 56  1 55 56  1 28 60 58 65 56
 10  0 27  4 94 71 52 60 71  1 72 65  1 73 60 56 60 63 63 52 69 55  1 55
  4 56 65 73 60 69 66 65  1 70 66 60 75 52 65 71 56  9 68 72 60 65 77 56
  1 52 65 70 23  1 60 63  1 66 54 54 72 67 52 60 71  1 63 56  1 70 60 93
 58 56  0 55 56  1 28 60 58 65 56  1 55 56 67 72 60 70  1 13 20 12 18 10
  0  0 41 72 66 60 68 72 56  1 54 56  1 55 94 71 52 60 63  1 65 56  1 71
 66 72 54 59 56  1 56 65  1 52 72 54 72 65 56  1 64 52 65 60 93 69 56  1
 52 72  1 57 66 65 55  1 64 95]
['C' 'h' 'a' 'p' 'i' 't' 'r' 'e' ' ' 'I' '\n' '\n' 'M' 'o' 'n' 's' 'i' 'e'
 'u' 'r' ' ' 'M' 'y' 'r' 'i' 'e' 'l' '\n' '\n' '\n' 'E' 'n' ' ' '1' '8'
 '1' '5' ',' ' ' 'M' '.' ' ' 'C' 'h' 'a' 'r' 'l' 'e' 's' '-' 'F' 'r' 'a'
 'n' 'ç' 'o' 'i' '

In [ ]:
# Maintenant on peut joindre tout ça pour que ce soit une liste
print(''.join(index_par_caractere[input_texte.numpy()]))

Chapitre I

Monsieur Myriel


En 1815, M. Charles-François-Bienvenu Myriel était évêque de Digne.
C'était un vieillard d'environ soixante-quinze ans; il occupait le siège
de Digne depuis 1806.

Quoique ce détail ne touche en aucune manière au fond mê


In [ ]:
# on peut afficher le texte cible
print(cible_texte.numpy())
print(''.join(index_par_caractere[cible_texte.numpy()]))

[59 52 67 60 71 69 56  1 33  0  0 37 66 65 70 60 56 72 69  1 37 76 69 60
 56 63  0  0  0 29 65  1 13 20 13 17  8  1 37 10  1 27 59 52 69 63 56 70
  9 30 69 52 65 92 66 60 70  9 26 60 56 65 73 56 65 72  1 37 76 69 60 56
 63  1 94 71 52 60 71  1 94 73 95 68 72 56  1 55 56  1 28 60 58 65 56 10
  0 27  4 94 71 52 60 71  1 72 65  1 73 60 56 60 63 63 52 69 55  1 55  4
 56 65 73 60 69 66 65  1 70 66 60 75 52 65 71 56  9 68 72 60 65 77 56  1
 52 65 70 23  1 60 63  1 66 54 54 72 67 52 60 71  1 63 56  1 70 60 93 58
 56  0 55 56  1 28 60 58 65 56  1 55 56 67 72 60 70  1 13 20 12 18 10  0
  0 41 72 66 60 68 72 56  1 54 56  1 55 94 71 52 60 63  1 65 56  1 71 66
 72 54 59 56  1 56 65  1 52 72 54 72 65 56  1 64 52 65 60 93 69 56  1 52
 72  1 57 66 65 55  1 64 95 64]
hapitre I

Monsieur Myriel


En 1815, M. Charles-François-Bienvenu Myriel était évêque de Digne.
C'était un vieillard d'environ soixante-quinze ans; il occupait le siège
de Digne depuis 1806.

Quoique ce détail ne touche en aucune manière

In [ ]:
# Choisir une taille de lot
taille_batch = 128

# On va le laisser mélanger toute la séquence en mémoire uniquement
# Pour éviter un texte trop gros, qui provoquerait des erreurs
memoire_tampon = 1000

# Shuffle() pour les mélanger et batch() pour les prendre en compte
dataset = dataset.shuffle(memoire_tampon).batch(taille_batch, drop_remainder=True)

dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 250), dtype=tf.int64, name=None), TensorSpec(shape=(128, 250), dtype=tf.int64, name=None))>

# Création du modèle

In [ ]:
# La longueur de notre vocabulaire
vocabulaire_size = len(vocabulaire)
print(vocabulaire_size)

105


In [ ]:
# Pour notre couche de embedding, on va définir la dimension embedding
#Une trop grande valeur entrainera des features inutiles
embed_dimension = 85

In [ ]:
# Une couche RNN avec le GRU
# Choisir le nbre de neurones (il doit etre conséquent)
rnn_neurones = 1026

# Fonction de perte (appelé loss)

In [ ]:
# import
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [ ]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1, ignore_class=None)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    >>> y_true = [[[ 0,  2],
    ...            [-1, -1]],
    ...           [[ 0,  2],
    ...            [-1, -1]]]
    >>> y_pred = [[[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],
    ...             [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]],
    ...           [[[1.0, 0.0, 0.0], [0.0, 0.5, 0.5]],
    ...            [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(
    ...   y_true, y_pred, ignore_class=-1)
    >>> loss.numpy()
    array([[[2.384

In [ ]:
# Créer la fonction de perte
def perte_categorielle(y_true, y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [ ]:
# Création du modele

# Imports
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense

# Fonction
def create_modele(vocabulaire_size, embed_dimension, rnn_neurones, taille_batch):
  modele = Sequential()

  modele.add(Embedding(vocabulaire_size, embed_dimension, batch_input_shape=[taille_batch, None]))
  modele.add(GRU(rnn_neurones, return_sequences=True, stateful=True, recurrent_initializer='glorot_uniform'))
  modele.add(Dense(vocabulaire_size))

  modele.compile(optimizer='adam',loss=perte_categorielle)

  return modele

In [ ]:
modele = create_modele(vocabulaire_size=vocabulaire_size,
                       embed_dimension= embed_dimension,
                       rnn_neurones=rnn_neurones,
                       taille_batch=taille_batch)

In [ ]:
modele.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (128, None, 85)           8925      
                                                                 
 gru_2 (GRU)                 (128, None, 1026)         3425814   
                                                                 
 dense_2 (Dense)             (128, None, 105)          107835    
                                                                 
Total params: 3,542,574
Trainable params: 3,542,574
Non-trainable params: 0
_________________________________________________________________


# Entrainement du modele

### Verification du code , si tout est ok

In [ ]:
# Executer le modele sur un batch d'entrée
for batch_texte_exemple, batch_cible_exemple in dataset.take(1):
  exemple_batch_prediction = modele(batch_texte_exemple)

exemple_batch_prediction.shape

TensorShape([128, 250, 105])

In [ ]:
# Premier element
exemple_batch_prediction[0]

<tf.Tensor: shape=(250, 105), dtype=float32, numpy=
array([[ 5.1518474e-03,  1.9271219e-03,  2.4171779e-05, ...,
         1.1323937e-03,  1.0207861e-03,  1.0992355e-02],
       [ 1.3680205e-03,  3.1512084e-03,  8.3188657e-03, ...,
        -1.1648999e-03, -1.3975953e-03,  9.4194449e-03],
       [-3.7204302e-03,  5.3808433e-03, -2.5735563e-03, ...,
        -2.8853910e-04,  1.0330009e-04, -2.5053713e-03],
       ...,
       [-6.7539765e-03, -5.1646526e-03, -9.7643249e-03, ...,
        -5.5138674e-03, -7.6250331e-03,  2.2871559e-04],
       [-5.6019891e-03, -9.2105824e-04,  4.6105525e-03, ...,
        -5.2402294e-03, -7.5906450e-03,  4.9012406e-03],
       [ 3.5162112e-03, -5.8422890e-04,  9.5229922e-04, ...,
        -2.3520177e-03,  6.0776970e-04,  3.2177595e-03]], dtype=float32)>

In [ ]:
# On va ajouter un nbre d'echantillon a saisir
echantillon_indices = tf.random.categorical(exemple_batch_prediction[0], num_samples=1)

print(echantillon_indices)

tf.Tensor(
[[ 75]
 [  6]
 [ 51]
 [ 83]
 [ 62]
 [ 98]
 [ 79]
 [100]
 [ 35]
 [ 33]
 [ 10]
 [ 20]
 [ 21]
 [  3]
 [ 73]
 [ 74]
 [102]
 [103]
 [103]
 [ 73]
 [ 69]
 [ 18]
 [ 79]
 [100]
 [100]
 [ 70]
 [ 74]
 [ 20]
 [ 90]
 [ 48]
 [ 55]
 [ 39]
 [ 29]
 [ 94]
 [  1]
 [ 63]
 [102]
 [ 74]
 [ 51]
 [  0]
 [ 68]
 [ 39]
 [ 36]
 [ 96]
 [ 47]
 [ 62]
 [ 78]
 [ 49]
 [ 31]
 [ 12]
 [ 34]
 [100]
 [ 66]
 [ 38]
 [ 31]
 [  0]
 [ 11]
 [ 16]
 [ 19]
 [ 31]
 [ 40]
 [ 50]
 [ 17]
 [ 33]
 [ 16]
 [ 13]
 [ 38]
 [ 89]
 [  2]
 [ 71]
 [ 51]
 [ 36]
 [ 19]
 [ 17]
 [ 74]
 [ 51]
 [ 83]
 [ 34]
 [ 26]
 [ 23]
 [  0]
 [ 10]
 [ 51]
 [ 62]
 [ 86]
 [ 96]
 [ 12]
 [ 36]
 [ 62]
 [ 42]
 [ 35]
 [ 70]
 [ 66]
 [ 93]
 [ 22]
 [ 21]
 [ 38]
 [ 66]
 [ 30]
 [ 20]
 [ 50]
 [ 87]
 [ 75]
 [ 21]
 [ 51]
 [ 77]
 [ 53]
 [ 87]
 [ 24]
 [ 94]
 [ 51]
 [ 12]
 [ 31]
 [ 76]
 [ 87]
 [ 94]
 [ 88]
 [ 40]
 [100]
 [ 53]
 [ 70]
 [ 60]
 [ 55]
 [ 98]
 [ 42]
 [ 33]
 [ 33]
 [ 76]
 [ 85]
 [ 89]
 [ 47]
 [ 73]
 [  4]
 [ 25]
 [ 85]
 [  2]
 [ 99]
 [ 73]
 [ 44]
 [ 31]
 [ 46]
 [

In [ ]:
# Passer le tableau dans notre sequence "caractere_par_index"
# Pour ca, je dois le reformater
echantillon_indices = tf.squeeze(echantillon_indices, axis=1).numpy()

echantillon_indices

array([ 75,   6,  51,  83,  62,  98,  79, 100,  35,  33,  10,  20,  21,
         3,  73,  74, 102, 103, 103,  73,  69,  18,  79, 100, 100,  70,
        74,  20,  90,  48,  55,  39,  29,  94,   1,  63, 102,  74,  51,
         0,  68,  39,  36,  96,  47,  62,  78,  49,  31,  12,  34, 100,
        66,  38,  31,   0,  11,  16,  19,  31,  40,  50,  17,  33,  16,
        13,  38,  89,   2,  71,  51,  36,  19,  17,  74,  51,  83,  34,
        26,  23,   0,  10,  51,  62,  86,  96,  12,  36,  62,  42,  35,
        70,  66,  93,  22,  21,  38,  66,  30,  20,  50,  87,  75,  21,
        51,  77,  53,  87,  24,  94,  51,  12,  31,  76,  87,  94,  88,
        40, 100,  53,  70,  60,  55,  98,  42,  33,  33,  76,  85,  89,
        47,  73,   4,  25,  85,   2,  99,  73,  44,  31,  46,  66,  45,
        61,  16,  16,   4,  81,  95,  47,   7,  80,  26,  59,  40,  53,
        40,  99,  29,  82,   0,  23,  47,  71,   0, 103,  57,  30,  36,
        54,  32,  23,  80,  12,  30,   4,  63,  38,  70,  15,  8

In [ ]:
# passer mon echantillon en index_par_caractere
index_par_caractere[echantillon_indices]

array(['x', ')', '_', 'Â', 'k', 'ï', '°', 'ô', 'K', 'I', '.', '8', '9',
       '"', 'v', 'w', 'ù', 'û', 'û', 'v', 'r', '6', '°', 'ô', 'ô', 's',
       'w', '8', 'â', 'X', 'd', 'O', 'E', 'é', ' ', 'l', 'ù', 'w', '_',
       '\n', 'q', 'O', 'L', 'ë', 'W', 'k', '«', 'Y', 'G', '0', 'J', 'ô',
       'o', 'N', 'G', '\n', '/', '4', '7', 'G', 'P', 'Z', '5', 'I', '4',
       '1', 'N', 'à', '!', 't', '_', 'L', '7', '5', 'w', '_', 'Â', 'J',
       'B', ';', '\n', '.', '_', 'k', 'É', 'ë', '0', 'L', 'k', 'R', 'K',
       's', 'o', 'è', ':', '9', 'N', 'o', 'F', '8', 'Z', 'Ê', 'x', '9',
       '_', 'z', 'b', 'Ê', '?', 'é', '_', '0', 'G', 'y', 'Ê', 'é', 'Ô',
       'P', 'ô', 'b', 's', 'i', 'd', 'ï', 'R', 'I', 'I', 'y', 'È', 'à',
       'W', 'v', "'", 'A', 'È', '!', 'ñ', 'v', 'T', 'G', 'V', 'o', 'U',
       'j', '4', '4', "'", '»', 'ê', 'W', '*', 'º', 'B', 'h', 'P', 'b',
       'P', 'ñ', 'E', 'À', '\n', ';', 'W', 't', '\n', 'û', 'f', 'F', 'L',
       'c', 'H', ';', 'º', '0', 'F', "'", 'l', 'N', 's', '3

### Entrainement

In [ ]:
# Il faut un nbre réaliste , sur un modele type génération de texte
## je ne devrais pâs etre en dessous de minimum 30 epochs
epochs = 25

In [ ]:
modele.fit(dataset, epochs=epochs)

Epoch 1/25
76/76 [==============================] - 30s 348ms/step - loss: 3.1349
Epoch 2/25
76/76 [==============================] - 25s 320ms/step - loss: 2.3656
Epoch 3/25
76/76 [==============================] - 24s 305ms/step - loss: 2.1766
Epoch 4/25
76/76 [==============================] - 26s 331ms/step - loss: 2.0110
Epoch 5/25
76/76 [==============================] - 24s 310ms/step - loss: 1.8552
Epoch 6/25
76/76 [==============================] - 23s 303ms/step - loss: 1.7162
Epoch 7/25
76/76 [==============================] - 25s 327ms/step - loss: 1.5998
Epoch 8/25
76/76 [==============================] - 24s 315ms/step - loss: 1.5072
Epoch 9/25
76/76 [==============================] - 23s 301ms/step - loss: 1.4326
Epoch 10/25
76/76 [==============================] - 25s 328ms/step - loss: 1.3761
Epoch 11/25
76/76 [==============================] - 24s 310ms/step - loss: 1.3292
Epoch 12/25
76/76 [==============================] - 25s 318ms/step - loss: 1.2923
Epoch 13/25
7

In [ ]:
# Sauvegarde du modele
modele.save("/content/LesMiserables.h5")

# Prédiction - Génération de texte

### Ajuster la taille du batch de 128 et le passer à 1

In [ ]:
from tensorflow.python import rnn
# on va crer un nouveau modele
modele = create_modele(vocabulaire_size, embed_dimension, rnn_neurones, taille_batch=1)
# On charge les poids du modele sauvegardé
modele.load_weights('LesMiserables.h5')
# construction avec forme d'entrée Tensorshape de 1 par none
modele.build(tf.TensorShape([1, None]))

# Résumé de ce nouveau modele
modele.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (1, None, 85)             8925      
                                                                 
 gru_3 (GRU)                 (1, None, 1026)           3425814   
                                                                 
 dense_3 (Dense)             (1, None, 105)            107835    
                                                                 
Total params: 3,542,574
Trainable params: 3,542,574
Non-trainable params: 0
_________________________________________________________________


### fonction pour la génération de texte

In [ ]:
def prediction_texte(modele, start_seed, gen_size=500, temp=0.3):
  nb_caracteres_generes = gen_size
  # on vectorise le texte du seed de depart
  # on va devoir le transformer en caractere par index
  input_seed = [caractere_par_index[s] for s in start_seed]
  # on etend les dimensions pour correspondre au format batch
  input_seed = tf.expand_dims(input_seed, 0)

  # on créer notre liste vide qui contiendra notre resultat
  texte_predit = []
  # On peut lui donner une temperature
  temperature = temp

  # on remet à zéro l'état du modele
  modele.reset_states()

  # et on boucle sur le nbre de caracteres souhaités
  for i in range(nb_caracteres_generes):
    # on génère des prédictions
    predictions = modele(input_seed)
    # on supprime la forme du batch
    predictions = tf.squeeze(predictions, 0)

    # on utilise une distribution catégorielle pour selectionner le caractère suivant
    predictions = predictions / temperature
    # puis l'index predit en lui passant les predictions et le nb d'echantillons
    # on va aussi faire un peu d'indexage pour avoir uniquement notre index
    prediction_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

    # on passe le caractere predit pour la prochaine entrée (un pas en avant)
    input_seed = tf.expand_dims([prediction_id], 0)

    # on retransforme d'index par caractere
    texte_predit.append(index_par_caractere[prediction_id])

  # on retourne le start seed correspondant au mot de départ, en joignant le texte predit
  # à la suite
  return (start_seed+''.join(texte_predit))


### faire une generation

In [ ]:
print(prediction_texte(modele, "Je suis sortie de la maison de bonne heure", gen_size=1000))

Je suis sortie de la maison de bonne heure, il avait
conservé les propriétaires de l'épouvante, les passants voyaient des ressources, et
de l'autre le point de vue de la foule et d'abord contre le mur
de cette maison de la rue de l'Homme-Armé.

--Je ne vous passerai pas.

--Et les petits conseils de l'événement des petits conseils de conseil de ce
mot d'ordre se remit à marcher dans le coeur des passants. Il
se retourna et dit:

--Vous êtes parti tout ce qui s'appelle la barricade!

Cependant il s'appelait Marius qui s'était mis à lui dire:

--Vous m'avez donc pas moins que le coeur de ce monde et la misère. Le
progrès n'avait pas dit qu'il n'avait pas de chose qu'un poteau pour le
salut de la contre-coup de police de l'éléphant.

Le prisonnier ne pouvait se retourner dans les proclamations de l'argot
de l'homme qui avait laissé de se dire qu'il avait apporté un homme qui
s'était posé sur le boulevard de la rue de la Chanvrerie, et le soleil s'appelle trois mois
aux passants de l'émeut